language: java
jdk:
  - oraclejdk8

before_install: cd proyecto
install: ant

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - nmarianetti@fi.uba.ar
      - ateston@fi.uba.ar
      - gonzalomartinezsastre@gmail.com
      - nariedel99@gmail.com
on_failure: always




