language: java
jdk:
  - oraclejdk8

install: ant

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - nmarianetti@fi.uba.ar
      - ateston@fi.uba.ar
on_failure: always
